# Generated by Django 2.2.6 on 2019-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_by', 'email'],
                'get_latest_by': 'created_by',
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(age__gte=14), name='age_gte_14'),
        ),
    ]
